[versions]
kotlin = "2.0.20"
jupiter = "5.11.0"

pluginPublishPlugin = "1.2.2"
gitVersionerPlugin = "1.6.7"
indexScanPlugin = "2.8.3"
owaspPlugin = "10.0.4"
cycloneDxBomPlugin = "1.10.0"
licenseePlugin = "1.11.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
jupiter-core = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }

[plugins]
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublishPlugin" }
versioner = { id = "io.toolebox.git-versioner", version.ref = "gitVersionerPlugin" }
index-scan = { id = "org.sonatype.gradle.plugins.scan", version.ref = "indexScanPlugin" }
owasp-dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "owaspPlugin" }
cyclonedx-bom = { id = "org.cyclonedx.bom", version.ref = "cycloneDxBomPlugin" }
licensee-plugin = { id = "app.cash.licensee", version.ref = "licenseePlugin" }
