# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JavaCI

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "**/README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "pull_request_template.md"
      - "SECURITY.md"
      - "LICENSE"
      - ".github/**"
      - "renovate.json"
      - ".whitesource"
      - "gradle/libs.versions.toml"
      - "gradle/verification-metadata.xml"
      - "gradle/verification-metadata-clean.xml"
      - "gradle/wrapper/gradle-wrapper.properties"
      - ".qlty/**"

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set up build environment
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLISH_KEY }}
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
      - name: Set up JDK 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
        with:
          gradle-home-cache-cleanup: true
      - name: Build with Gradle
        run: >
          ./gradlew tagVersion build 
          -PgithubUser=${{ secrets.PUBLISH_USER_NAME }} 
          -PgithubToken=${{ secrets.PUBLISH_KEY }}
      - name: Publish with Gradle
        run: >
          ./gradlew publish publishPlugins
          -PgithubUser=${{ secrets.PUBLISH_USER_NAME }}
          -PgithubToken=${{ secrets.PUBLISH_KEY }}
          -Pgradle.publish.key=${{ secrets.GRADLE_KEY }}
          -Pgradle.publish.secret=${{ secrets.GRADLE_SECRET }}
