# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JavaCI-PR

on:
  push:
    branches: [main]
    paths:
      - "gradle/libs.versions.toml"
      - "gradle/verification-metadata.xml"
      - "gradle/wrapper/gradle-wrapper.properties"
      - ".github/workflows/gradle-ci.yml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "**/README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "pull_request_template.md"
      - "SECURITY.md"
      - "LICENSE"
      - ".github/**"
      - "!.github/workflows/gradle-ci.yml"
      - "renovate.json"
      - ".whitesource"
      - ".qlty/**"

permissions: read-all

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Set up build environment
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      - name: Setup JDK 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      - name: Build with Gradle
        run: ./gradlew printVersion build
      - name: Upload Test reports
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: test-report-run-dash-license-tool-gradle-plugin-${{ matrix.os }}
          path: build/reports/tests/test
          retention-days: 5
