# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JavaCI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '**/README.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'pull_request_template.md'
      - 'SECURITY.md'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/assets/**'
      - '.github/workflows/**'
      - '.github/pr-labeler.yml'
      - 'renovate.json'
      - '.whitesource'
      - 'gradle/libs.versions.toml'
      - 'gradle/verification-metadata.xml'
      - 'gradle/verification-metadata-clean.xml'
      - 'gradle/wrapper/gradle-wrapper.properties'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set up build environment
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLISH_KEY }}
      - name: Set up JDK 17
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          gradle-home-cache-cleanup: true
      - name: Build with Gradle
        run: >
          ./gradlew tagVersion build 
          -PgithubUser=${{ secrets.PUBLISH_USER_NAME }} 
          -PgithubToken=${{ secrets.PUBLISH_KEY }}
      - name: Publish with Gradle
        run: >
          ./gradlew publish publishPlugins
          -PgithubUser=${{ secrets.PUBLISH_USER_NAME }}
          -PgithubToken=${{ secrets.PUBLISH_KEY }}
          -Pgradle.publish.key=${{ secrets.GRADLE_KEY }}
          -Pgradle.publish.secret=${{ secrets.GRADLE_SECRET }}
